markdown: kramdown
permalink: /:title
url: "http://nodeschool.io/toronto"
timezone: America/Toronto

kramdown:
  input: GFM

# Use the following plug-ins
gems:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: :compressed

# Exclude these files from your production _site
exclude:
  - README.md
  - .editorconfig
  - Procfile
  - .sass-cache/
  - tasks/

mentors:
  - name: ricky
    twitter: rickycodes
  - name: jeff
    twitter: jeffjewiss
  - name: brenna
    twitter: brnnbrn
  - name: darcy
    twitter: darcy
  - name: rich
    twitter: richgilbank
  - name: andrew
    twitter: andrewdamelio
  - name: tessa
    twitter: tessthornton
  - name: ahmad
    twitter: ahmadnassri
  - name: ryan
    twitter: RChristiani
  - name: vlad
    twitter: vladikoff
  - name: jeremiah
    twitter: Fishrock123
  - name: jordan
    twitter: jrdnndtsch
  - name: wisam
    twitter: wisamjs
  - name: neil
    twitter: neil_fenton
  - name: chris
    twitter: chrismendis
